# Generated by Django 3.2.23 on 2024-03-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
    ]
