# Generated by Django 3.2.21 on 2023-11-02 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdynmaic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formdynmaic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formdynmaic',
            name='price',
        ),
    ]
