# Generated by Django 3.2.23 on 2024-03-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
