# Generated by Django 3.2.21 on 2023-11-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20231102_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formdynmaic',
            options={'verbose_name_plural': 'Category form'},
        ),
    ]
