# Generated by Django 3.2.23 on 2023-11-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20231103_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.contactus'),
        ),
    ]
