# Generated by Django 3.2.23 on 2023-11-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactCategory',
        ),
    ]
