# Generated by Django 3.2.23 on 2023-11-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_formdynmaic_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormDynmaic',
        ),
    ]
