# Generated by Django 3.2.21 on 2023-10-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contactcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'verbose_name_plural': 'Contact for Hire Me'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Categories'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactus.contactcategory'),
        ),
    ]
