# Generated by Django 3.2.21 on 2023-10-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20231027_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdynmaic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contactus.contactcategory'),
        ),
    ]
