# Generated by Django 3.2.21 on 2023-10-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elenainfo',
            old_name='title',
            new_name='head',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sku',
        ),
    ]
