# Generated by Django 3.2.21 on 2023-10-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231029_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
