# Generated by Django 3.2.21 on 2023-10-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
    ]
