# Generated by Django 3.2.21 on 2023-10-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20231028_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('bio', models.TextField()),
            ],
        ),
    ]
