# Generated by Django 3.2.23 on 2023-11-05 17:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('head', models.CharField(max_length=254)),
                ('info', models.TextField()),
            ],
        ),
    ]
