# Generated by Django 3.2.23 on 2024-03-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_exhibationview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibationview',
            name='sku',
        ),
    ]
