# Generated by Django 3.2.21 on 2023-10-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_categories_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_groups',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
