# Generated by Django 3.2.21 on 2023-10-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_categories_groups_categoriesgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesgroups',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
