# Generated by Django 3.2.21 on 2023-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categoriesgroups_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesgroups',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
