# Generated by Django 3.2.23 on 2023-11-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_categoriesgroups_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
